apiVersion: apps/v1
kind: Deployment
metadata:
  name: faro-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: faro-application
  template:
    metadata:
      labels:
        app: faro-application
    spec:
      containers:
      - name: faro-application
        image: faroprodregistry.azurecr.io/Ooffuss1453/faro-application:11
        ports:
        - containerPort: 5000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: farosolutions-app-svc
spec:
  selector:
    app: farosolutions-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
